name: train_me
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  meta: ^1.11.0
  intl: ^0.20.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  path: ^1.9.0
  firebase_storage: ^12.3.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_messaging: ^15.1.5
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.3
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.35.2
  health: ^12.0.1
  syncfusion_flutter_charts: ^28.2.5+1
  provider: ^6.1.2
  shared_preferences: ^2.5.2

flutter_native_splash:
  color: "#000000"
  image: assets/images/freepik-untitled-project-202502222126512ePt.png
  image_dark: assets/images/freepik-untitled-project-202502222126512ePt.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/WhatsApp Image 2025-02-14 at 20.48.37_58a1ebff.jpg"

flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
